# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assets', models.FloatField()),
                ('total_current_assets', models.FloatField()),
                ('total_liabilities', models.FloatField()),
                ('total_current_liabilities', models.FloatField()),
                ('debt', models.FloatField()),
                ('net_income', models.FloatField(help_text='Always estimated for the whole year.')),
                ('share_price_soles', models.FloatField()),
                ('total_shares', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.Year'),
        ),
    ]
