# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 13:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='share',
            field=models.CharField(default=datetime.datetime(2016, 1, 17, 13, 6, 34, 268013, tzinfo=utc), help_text='Share code: for example continc1', max_length=200),
            preserve_default=False,
        ),
    ]
