# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0002_financialstatement_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialstatement',
            old_name='share',
            new_name='security_code',
        ),
    ]
